

title: Color Variables
email: des@example.com
description: hi
baseurl: "" 
url: ""
twitter_username: des
github_username:  des
destination: docs

# Build settings

plugins:
  - jekyll-feed


#  exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
# - node_modules/
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/
